name: Deploy to Server

on:
  push:
    branches:
      - master  # Adjust branch as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSHpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            cd ${{ secrets.PROJECT_PATH }}
            git pull origin main
            pip install -r requirements.txt
            make mig
            systemctl restart ${{ secrets.SERVICE_NAME }} || pm2 restart all || echo "No service manager found"
            
          EOF
